import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

const SCORECARD_PROMPT = `You are an expert recruiter reviewing an AI-conducted screening interview. Analyze the transcript below and produce a structured scorecard.

The interview was for the role: "{campaignTitle}"
Campaign description: "{campaignDescription}"

Return a JSON object with this exact structure:
{
  "overall_score": <number 1-5>,
  "communication_score": <number 1-5>,
  "clarity_score": <number 1-5>,
  "articulation_score": <number 1-5>,
  "summary": "<2-3 sentence overall assessment>",
  "strengths": ["<strength 1>", "<strength 2>", ...],
  "concerns": ["<concern 1>", "<concern 2>", ...],
  "recommendation": "<Advance | Maybe | Pass>",
  "recommendation_reason": "<1 sentence explaining the recommendation>",
  "notable_quotes": ["<memorable quote from candidate>", ...]
}

Scoring dimensions (all focused on English proficiency):
- overall_score: Overall English proficiency level
- communication_score: Fluency and natural flow — can they speak English smoothly without long pauses, filler words, or struggling to form sentences?
- clarity_score: Pronunciation and intelligibility — can they be clearly understood? Are words pronounced correctly?
- articulation_score: Vocabulary and grammar — do they use appropriate words, correct grammar, and varied sentence structures?

Scoring guide:
- 5: Native / near-native — fluent, natural, effortless English
- 4: Advanced — very comfortable, minor non-native traits that don't hinder communication
- 3: Intermediate — functional English, some noticeable gaps but can hold a conversation
- 2: Below average — frequent grammar issues, limited vocabulary, hard to follow at times
- 1: Beginner — struggles significantly to communicate in English

Be fair and evidence-based. This is a screening round focused ONLY on English proficiency. Do NOT evaluate technical knowledge, domain expertise, or relevance to the role. Judge purely on how well the candidate can speak and understand English.

IMPORTANT CAVEAT: This transcript was generated by an AI speech-to-text model and may contain transcription errors — misheard words, garbled phrases, or short nonsensical fragments (e.g., foreign-sounding words that the candidate likely never said). Do NOT penalize the candidate for isolated odd words or phrases that look like transcription artifacts. Focus on the overall pattern of communication across the full conversation rather than individual anomalies. If a candidate is otherwise fluent and coherent but has a few strange fragments, those are almost certainly transcription errors, not proficiency issues.

IMPORTANT: Return ONLY the JSON object, no markdown formatting, no code blocks.`;

export async function POST(request: Request) {
  try {
    const { interviewId } = await request.json();

    if (!interviewId) {
      return NextResponse.json(
        { error: "Missing interviewId" },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    // Fetch interview with candidate and campaign info
    const { data: interview, error: fetchError } = await supabase
      .from("interviews")
      .select(
        `
        *,
        candidates(
          name,
          email,
          campaign_id,
          campaigns(title, description, questions)
        )
      `
      )
      .eq("id", interviewId)
      .single();

    if (fetchError || !interview) {
      return NextResponse.json(
        { error: "Interview not found" },
        { status: 404 }
      );
    }

    if (!interview.transcript || interview.transcript.length === 0) {
      return NextResponse.json(
        { error: "No transcript available" },
        { status: 400 }
      );
    }

    const candidate = interview.candidates as {
      name: string;
      email: string;
      campaign_id: string;
      campaigns: { title: string; description: string | null; questions: string[] };
    };

    // Format transcript for the prompt
    const formattedTranscript = interview.transcript
      .map(
        (entry: { role: string; content: string }) =>
          `${entry.role === "ai" ? "Interviewer" : candidate.name}: ${entry.content}`
      )
      .join("\n\n");

    const prompt = SCORECARD_PROMPT.replace(
      "{campaignTitle}",
      candidate.campaigns.title
    ).replace(
      "{campaignDescription}",
      candidate.campaigns.description || "No description provided"
    );

    // Call OpenAI
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o",
        messages: [
          { role: "system", content: prompt },
          {
            role: "user",
            content: `Here is the interview transcript:\n\n${formattedTranscript}`,
          },
        ],
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("OpenAI error:", errText);
      return NextResponse.json(
        { error: "Failed to analyze interview" },
        { status: 500 }
      );
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      return NextResponse.json(
        { error: "Empty response from AI" },
        { status: 500 }
      );
    }

    // Parse the JSON response
    let scorecard;
    try {
      scorecard = JSON.parse(content);
    } catch {
      // Try extracting JSON from markdown code blocks
      const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        scorecard = JSON.parse(jsonMatch[1]);
      } else {
        throw new Error("Failed to parse scorecard JSON");
      }
    }

    // Store scorecard and summary
    const { error: updateError } = await supabase
      .from("interviews")
      .update({
        scorecard,
        ai_summary: scorecard.summary,
      })
      .eq("id", interviewId);

    if (updateError) {
      console.error("Update error:", updateError);
      return NextResponse.json(
        { error: "Failed to save scorecard" },
        { status: 500 }
      );
    }

    return NextResponse.json({ scorecard });
  } catch (err) {
    console.error("Analyze error:", err);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
